import React,{useEffect,useMemo,useState} from 'react';
import './styles.css';
const fallbackTerritories=[
 {territory_key:'MAR',name_fr:'Maroc',region_type:'country',latitude:31.79,longitude:-7.09,climate_zone:'Mediterranean / Arid / Mountain'},
 {territory_key:'RABAT',name_fr:'Rabat',region_type:'city',latitude:34.02,longitude:-6.84,climate_zone:'Mediterranean'},
 {territory_key:'MARRAKECH',name_fr:'Marrakech',region_type:'city',latitude:31.63,longitude:-7.98,climate_zone:'Arid / Semi-arid'},
 {territory_key:'MERZOUGA',name_fr:'Merzouga',region_type:'locality',latitude:31.08,longitude:-4.01,climate_zone:'Arid / Desert'},
 {territory_key:'OUARZAZATE',name_fr:'Ouarzazate',region_type:'city',latitude:30.93,longitude:-6.94,climate_zone:'Arid / Mountain'},
 {territory_key:'AGADIR',name_fr:'Agadir',region_type:'city',latitude:30.43,longitude:-9.60,climate_zone:'Mediterranean / Coastal'},
 {territory_key:'ESSAOUIRA',name_fr:'Essaouira',region_type:'city',latitude:31.51,longitude:-9.76,climate_zone:'Coastal'},
 {territory_key:'IFRANE',name_fr:'Ifrane',region_type:'city',latitude:33.52,longitude:-5.11,climate_zone:'Mountain / Mediterranean'}
];
async function v30fetch(url,options){const r=await fetch(url,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Service V30 indisponible');return d}
export function V30App(){
 const [country,setCountry]=useState('MAR'),[territories,setTerritories]=useState(fallbackTerritories),[territory,setTerritory]=useState(fallbackTerritories[0]),[intent,setIntent]=useState(''),[session,setSession]=useState(null),[solutions,setSolutions]=useState([]),[health,setHealth]=useState([]),[signals,setSignals]=useState([]),[loading,setLoading]=useState(false),[status,setStatus]=useState(''),[api,setApi]=useState(true);
 useEffect(()=>{v30fetch('/api/platform/v30/territories/'+country).then(d=>{const list=d.territories||[];setTerritories(list.length?list:fallbackTerritories);setTerritory(list[0]||fallbackTerritories[0])}).catch(()=>setApi(false))},[country]);
 useEffect(()=>{v30fetch('/api/platform/v30/pro/opportunity-signals?territoryKey='+encodeURIComponent(territory.territory_key)).then(d=>setSignals(d.signals||[])).catch(()=>setSignals([]))},[territory.territory_key]); const cityTerritories=useMemo(()=>territories.filter(t=>t.region_type!=='country'),[territories]);
 const selectTerritory=async t=>{setTerritory(t);setSolutions([]);setHealth([]);setStatus('');try{const d=await v30fetch('/api/platform/v30/territory/'+t.territory_key);setHealth(d.healthSafety||[])}catch{setHealth([])}};
 const explore=async raw=>{const text=raw.trim();if(!text)return;setLoading(true);setStatus('');try{let s=session;if(!s){const d=await v30fetch('/api/platform/v30/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({countryIso3:country,territoryKey:territory.territory_key})});s=d.session;setSession(s)}await v30fetch('/api/platform/v30/session/'+s.id+'/intent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rawText:text})});const d=await v30fetch('/api/platform/v30/session/'+s.id+'/solutions');setSolutions(d.solutions||[]);const td=await v30fetch('/api/platform/v30/territory/'+(d.territory||territory.territory_key));setHealth(td.healthSafety||[]);setStatus('Recherche structurée prête — vous gardez la décision.')}catch(e){setApi(false);setStatus('Le parcours visuel reste disponible. Le moteur V30 sera reconnecté dès que le serveur est lancé.')}finally{setLoading(false)}};
 return <div className="v30app"><header className="v30header"><div><span className="v30brand">✦ LA TOILE</span><small>FIRST LIVING TOURISM PLATFORM · V30</small></div><div className="v30status"><i className={api?'live':'demo'}></i>{api?'MOTEUR CONNECTÉ':'MODE VISUEL'}</div></header><main>
 <section className="v30hero"><div className="v30globe"><div className="v30orbit"></div><div className="v30orbit second"></div><div className="v30sphere"><span className="v30continent c1"></span><span className="v30continent c2"></span><span className="v30continent c3"></span><span className="v30light l1"></span><span className="v30light l2"></span><span className="v30light l3"></span></div><div className="v30globeLabel">MONDE · HÉMISPHÈRES · CLIMATS</div></div>
 <div className="v30intro"><span className="eyebrow">GLOBE → TERRITOIRE → INTENTION → SOLUTIONS</span><h1>Le monde devient votre <em>interface de voyage.</em></h1><p>Explorez un territoire, dites simplement ce que vous recherchez. La Toile relie géographie, climat, tourisme, professionnels et Santé & Sécurité.</p><div className="v30intent"><span>✦</span><input value={intent} onChange={e=>setIntent(e.target.value)} onKeyDown={e=>e.key==='Enter'&&explore(intent)} placeholder="Ex. découvrir le désert avec ma famille…"/><button onClick={()=>explore(intent)} disabled={loading}>{loading?'Analyse…':'Explorer'}</button></div><div className="v30examples">{['Découvrir l’artisanat à Marrakech','Un séjour senior à Agadir','Le désert à Merzouga','Culture et patrimoine à Rabat'].map(x=><button key={x} onClick={()=>{setIntent(x);explore(x)}}>{x}</button>)}</div></div></section>
 <section className="v30workspace"><div className="v30territoryPanel"><div className="eyebrow">MAROC · TERRITOIRE PILOTE</div><h2>{territory.name_fr}</h2><p>{territory.climate_zone||'Climat à enrichir par le Climate Engine'} · Hémisphère nord</p><div className="v30cities">{cityTerritories.map(t=><button className={territory.territory_key===t.territory_key?'selected':''} key={t.territory_key} onClick={()=>selectTerritory(t)}>{t.name_fr}</button>)}</div><div className="v30principles"><span>01</span><b>Le voyageur décide</b><small>La Toile recommande, explique et compare sans choisir à votre place.</small></div><div className="v30principles"><span>02</span><b>Une couche Santé & Sécurité</b><small>Médecine, pharmacies, sécurité et assistance font partie du territoire.</small></div></div>
 <div className="v30results"><div className="v30resultHead"><div><span className="eyebrow">SOLUTIONS DU TERRITOIRE</span><h2>{solutions.length?solutions.length+' possibilités':'Que voulez-vous vivre ici ?'}</h2></div><span className="v30badge">{territory.climate_zone||'CLIMAT'}</span></div>{solutions.length?<div className="v30cards">{solutions.map(s=><article key={s.id}><span>{s.solution_type.replace('_',' ')}</span><h3>{s.title}</h3><p>{s.description}</p><small>{s.provider_name} · Compatibilité {s.match_score}%</small></article>)}</div>:<div className="v30empty"><div>✦</div><strong>Votre recherche commence ici.</strong><p>Choisissez une ville puis exprimez votre intention. Le moteur préparera les solutions compatibles.</p></div>}<div className="v30health"><div><span className="eyebrow">SANTÉ & SÉCURITÉ</span><h3>Autour de {territory.name_fr}</h3></div><div className="v30healthItems">{(health.length?health:[{service_type:'medicine',name:'Médecine à proximité'},{service_type:'pharmacy',name:'Pharmacies à proximité'},{service_type:'security',name:'Sécurité & assistance'}]).map((x,i)=><div key={x.id||i}><b>{x.service_type==='medicine'?'✚':x.service_type==='pharmacy'?'⌂':'◈'}</b><span>{x.name}</span></div>)}</div></div>{status&&<div className="v30notice">{status}</div>}</div><section className="v30opportunityPanel"><div><span className="eyebrow">INTELLIGENCE PRO→PRO</span><h2>Opportunités détectées sur ce territoire</h2><p>La Toile identifie des complémentarités entre professionnels. Rien n’est publié automatiquement : le professionnel reste décisionnaire.</p></div><div className="v30signalGrid">{signals.length?signals.slice(0,3).map(s=><article key={s.id}><span className="v30signalScore">{Math.round(Number(s.score))}%</span><h3>{s.title}</h3><p>{s.rationale}</p><small>{s.source_name||'Professionnel'} ↔ {s.target_name||'Professionnel'}</small></article>):<div className="v30emptySignal">Aucun signal d’opportunité disponible pour le moment.</div>}</div></section></section></main><footer className="v30footer"><span>LA TOILE · LIVING TOURISM GRAPH + GLOBAL CORE</span><span>V30.2 · TWO PILOT COUNTRIES</span></footer></div>
}
